name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    uses: cfandrews/ReusableWorkflows/.github/workflows/python-build.yml